# -*- coding: utf-8 -*-
"""main_script.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yZAKaZRB_wG1lrhFJClJWPOLEvJnTJdH
"""

# Added By Affan This function adds two numbers
def add_numbers(a, b):
    return a + b

#Hassaan bin kamran
name = "World"
print(f"Hello, {name}!")

#Haseeb Ahsan
print("Hello, World!")

#Ammar Shah adding a comment
print("Hello sir, how are you?")

#Abdullah Arif 
print("Hello sir, World!")